### ISSUE TITLE
Could you explain in detail what the pre-training weights mean in the given URL?

### ISSUE THREAD

**Issue by tengqi200** [stefanopini/simple-HRNet#1]
Thank you very much

**Comment by stefanopini** [comment]
My implementation of HRNet uses the same names and structures of the original implementation (but with a simpler and more readable code) so official pre-trained weights can be loaded using my code without requiring the train of the network from scratch.

Therefore, you can download and use any official pre-trained weight that is based on HRNet.  
With "pre-trained weights" I refer to the pre-trained models released by HRNet authors here:
[https://github.com/leoxiaobin/deep-high-resolution-net.pytorch#training-and-testing](https://github.com/leoxiaobin/deep-high-resolution-net.pytorch#training-and-testing).

For instance, you can find weights of many HRNet models trained on COCO here:
[https://drive.google.com/drive/folders/1nzM_OBV9LbAEA7HClC0chEyf_7ECDXYA](https://drive.google.com/drive/folders/1nzM_OBV9LbAEA7HClC0chEyf_7ECDXYA)

Have this answered to your question?

**Comment by tengqi200** [comment]
> Have this answered to your question?

Your answer is very helpful to me. I really appreciate it.

**Comment by stefanopini** [comment]
You're welcome :-)
