### ISSUE TITLE
TypeError: __init__() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by genkihoshino** [stefanopini/simple-HRNet#101]
Hi, I am running it on GoogleColaboratory.
The installation etc. should be working fine, but in the code '!python scripts/live-demo.py --filename sample.mp4' I get a 'Traceback (most recent call last):
  File "scripts/live-demo.py", line 185, in <module
    main(**args.__dict__)
  File "scripts/live-demo.py", line 67, in main
    device=device
  File "/content/drive/MyDrive/simple-HRNet/SimpleHRNet.py", line 136, in __init__
    device=device)
  File "/content/drive/MyDrive/simple-HRNet/models/detectors/YOLOv3.py", line 101, in __init__)
    self.model = Darknet(self.model_def,self.img_size).to(self.device)
I get an error 'TypeError: __init__() takes 2 positional arguments but 3 were given'.
The YOLO.py file has not been changed from the one in the repository.
I would be glad to know how to solve this problem.
Thank you in advance.

**Comment by stefanopini** [comment]
Hi, I'm happy you solved the issue! Could you post your solution for other people that may experience the same error?
