### ISSUE TITLE
有剪枝，蒸馏方面的计划吗？

### ISSUE THREAD

**Issue by APeiZou** [stefanopini/simple-HRNet#102]
@stefanopini  您好，有剪枝，蒸馏方面的计划吗？

**Comment by stefanopini** [comment]
Hi @APeiZou ,

Assuming your question is "Any plans for pruning and distillation?", I'm afraid no, I don't have plans to work on a pruned/distilled model in the future.
However, the repository contains a train script that could be adapted to train a distilled model from an existing one.

Alternatively, I can recommend using the smaller available version of YOLOv5 and the smaller version of HRNet (HRNet-32) to speed up the inference.

Please feel free to re-open if you have any other questions or you would like to contribute to the project 🙂
