### ISSUE TITLE
Use YOLOv5 as a detector

### ISSUE THREAD

**Issue by yan-ctrl** [stefanopini/simple-HRNet#106]
Hello, thank you for your excellent work. Can you tell me how to use YOLOv5 as a detector, or can you provide an explanation?

**Comment by stefanopini** [comment]
Hi @yan-ctrl , if you want to use YOLOv5, you can just set the parameters `yolo_version='v5', yolo_model_def='yolov5n'`, as shown in this [Google Colab notebook](https://colab.research.google.com/github/stefanopini/simple-HRNet/blob/master/SimpleHRNet_notebook.ipynb).

**Comment by yan-ctrl** [comment]
Okay, thank you
