### ISSUE TITLE
Is mpii model supported?

### ISSUE THREAD

**Issue by xtyDoge** [stefanopini/simple-HRNet#11]

**Comment by stefanopini** [comment]
Yes! Please check out the latest commit.

Now you can run the model using the official MPII weights with:
`python3 scripts/live-demo.py -w <your path>/simple-HRNet/weights/pose_hrnet_w32_256x256.pth --hrnet_c 32 --hrnet_j 16 --hrnet_joints_set mpii --image_resolution "(256, 256)"`

Please note that the code supports only the HRNet model. ResNet-based models are not supported.
