### ISSUE TITLE
[Question] Displaying the overlaid image ?

### ISSUE THREAD

**Issue by basicvisual** [stefanopini/simple-HRNet#13]
Hi , 
Is it possible to display the overlaid image on still images using the class usage example explained in the `readme` file . If so how can we do it ??

**Comment by stefanopini** [comment]
Hi,
If you mean how to show the skeleton on the input image, please look at the script `live-demo.py`, in particular to lines [62-65](https://github.com/stefanopini/simple-HRNet/blob/master/scripts/live-demo.py#L62-L65).

Referring to the example in the `readme`, you can just copy [that code](https://github.com/stefanopini/simple-HRNet/blob/master/scripts/live-demo.py#L62-L65) and replace `pts` with `joints` and `frame` with `image`.

**Comment by basicvisual** [comment]
Thank you ! @stefanopini , i was considering the case while we are doing  `2d pose estimation` and storing the `skeleton image`  for each frame for example in a folder .  I tried to follow the command `cv2.imwrite('frame.png', frame)`  but it only saved the png file for the last frame . Do you think we need to iterate this to save the skeleton per frame ?

**Comment by basicvisual** [comment]
Thank you for the pointers . i managed to get the overlaid image

**Comment by hatsumikana** [comment]
Hello! Thank you so much for creating this!

I am trying to get the overlaid image but failed to do so. I've pasted my code below, did I do something wrong?
```
import cv2
from SimpleHRNet import SimpleHRNet
from misc.visualization import draw_points

model = SimpleHRNet(48, 17, "./weights/pose_hrnet_w48_384x288.pth")
image = cv2.imread("image.png", cv2.IMREAD_COLOR)

joints = model.predict(image)
for joint in joints:
    frame = draw_points(image, joint)

cv2.imshow("image.png", frame)
```
