### ISSUE TITLE
Scaling YOLOv3 predictions instead of resize may have a better performance?

### ISSUE THREAD

**Issue by xtyDoge** [stefanopini/simple-HRNet#14]
The prediction of YOLOv3 usually a rectangle and I see that you use transforms method to resize the image before put it into HRNet. It stretching the image and make pose estimation network performs badly.
I try to make YOLOv3 prediction regions have the same h/w ratio as the input of HRNet. For example, HRNet requires image_resolution (256, 256)，but YOLOv3 gives a rectangle region. What we should do is calculate the center of YOLO prediction region and expand it as a square.

In `SimpleHRNet._predict_single`  I modify it by adding:
```
squareLen = max(x2 - x1, y2 - y1) // 2
centerX = x1 + (x2 - x1) // 2
centerY = y1 + (y2 - y1) // 2
x1 = max(0, centerX - squareLen)
x2 = min(len(image[1]), centerX + squareLen)
y1 = max(0, centerY - squareLen)
y2 = min(len(image[0]), centerY + squareLen)
```
And it works on pose_hrnet_w32_256x256 with mpii annotation. 
Maybe you can add it on your proj  :D

**Comment by stefanopini** [comment]
That's a cool idea, thank you! I will surely add it to the project, probably as an option.

Have you tested also with models pre-trained on COCO and bounding boxes with aspect ratio 4/3 (as `pose_hrnet_w32_256x192 `and `pose_hrnet_w48_384x288`)?

**Comment by xtyDoge** [comment]
@stefanopini Sorry I don't, maybe you can try it.

**Comment by stefanopini** [comment]
Added from commit [af40b39](https://github.com/stefanopini/simple-HRNet/commit/af40b392194caf4e8c646ce275382397da7a6a75)
Thank you for the suggestion!
