### ISSUE TITLE
Accessing specific keypoints and verlaying them on video ?

### ISSUE THREAD

**Issue by basicvisual** [stefanopini/simple-HRNet#15]
Hi , 
I was wondering how can we access the `x` and `y` co-ordinates of certain keypoints ?? For example right ankle_x and right ankle _y ??   
My aim is to calculate the angles between the joints and if possible show it overlaid on the video sequence ?

**Comment by stefanopini** [comment]
Hi!
The `predict` method of the `SimpleHRNet` class returns a ndarray of shape `people x joints x 3` where the last dimension contains the x, y coordinates and the confidence of each joint of each person.
Joint IDs are reported in `misc/visualization.py`.

For instance, right_ankle is the joint `16` therefore you can write
```
[...]
joints = model.predict(image)

person_ID = 0  # assuming one person
joint_ID = 16  # right_ankle
right_ankle = joints[person_ID, joint_ID]
```
where `right_ankle[0]` is the x coord, `right_ankle[1]` is the y coord, and `right_ankle[2]` is the joint confidence.

**Comment by timtensor** [comment]
I had a question, does `[person ID]]` correspond to `pose_entries` is a list of found poses (mentioned in open pose ??

**Comment by stefanopini** [comment]
I am not sure to understand what you mean, but I think the answer is no, `person_ID` is just the index of the i-th detected person by YOLOv3

**Comment by basicvisual** [comment]
Hi , two quick questions. When `disable _tracking` flag is not enabled we get the following output  This is for single person 
```
fps(array([[ 573,  120, 1283, 1067]], dtype=int32), array([[[2.2851042e+02, 8.9841669e+02, 9.8143256e-01],
        [2.0878125e+02, 9.0827777e+02, 9.9600869e-01],
        [2.0878125e+02, 8.7869446e+02, 9.5783162e-01],
        [1.8905208e+02, 9.6744446e+02, 9.7317010e-01],
        [2.0878125e+02, 8.7869446e+02, 5.8702219e-01],
        [2.7783334e+02, 9.9702777e+02, 9.0112782e-01],
        [2.8769791e+02, 8.8855554e+02, 9.2364275e-01],
        [2.8769791e+02, 8.3925000e+02, 9.0358442e-01],
        [3.2715625e+02, 7.4063892e+02, 9.5124328e-01],
        [2.7783334e+02, 7.6036108e+02, 8.2066935e-01],
        [2.5810416e+02, 8.0966669e+02, 1.0121015e+00],
        [5.8363544e+02, 9.5758331e+02, 8.1378901e-01],
        [5.9350000e+02, 8.9841669e+02, 7.7373838e-01],
        [7.5133331e+02, 7.8008331e+02, 9.0674573e-01],
        [7.3160419e+02, 1.0364722e+03, 8.7217093e-01],
        [1.0078125e+03, 8.0966669e+02, 8.4252542e-01],
        [8.4997919e+02, 1.1646666e+03, 9.1631120e-01]]], dtype=float32))

```



second , is it possible to see the person ID in the saved video file ??

**Comment by stefanopini** [comment]
First, which is the question?
With `return_bounding_boxes=True`, the first returned array are the person bounding boxes and the second returned array are the person keypoints.
With `return_bounding_boxes=False`, only the person keypoints are returned.

Second, at the moment no.

**Comment by Muhtasham** [comment]
Hi @stefanopini, 
Hope you are doing well, i wanted to ask how can i create a new keypoint after predicting the all the joints. My aim is to create Center of Mass and exploring this feature. 

Thank you very much for your time

**Comment by stefanopini** [comment]
Hi @Muhtasham 
Joints are returned in a numpy array with the format `(# of people, # of joints, 3)`.
You can just average on the second axis (the `# of joints` axis) to get the `(y, x, confidence)` coordinates of the center of mass.
A simple way to do that is `center_of_mass = np.mean(pts, axis=1)`, but you may want to ignore the joints with low confidence.

**Comment by basicvisual** [comment]
HI @stefanopini the above answer only works if tracking has been disabled am i right ? otherwise it raises an error . 

`TypeError: list indices must be integers or slices, not tuple`
