### ISSUE TITLE
Can i choose a different input size?

### ISSUE THREAD

**Issue by murdockhou** [stefanopini/simple-HRNet#16]
Hi, i'm tring to using hrnet with different input size, but there is wrong when I set input size is 192x144, seems like this model can only handle with input 256x192 and 384x288. Is there anyway should to make this work done? Thanks~

**Comment by stefanopini** [comment]
Hi,
the HRNet model halves and de-halves the input/the feature maps 5 consecutive times inside the network so the input width and height must be divisible by `2^5 = 32`.
Therefore, you can not use an input size of `192 x 144`, but you can use `192 x 160` or `192 x 128`.

That said, official weights are obtained training the model with input size 256x192 or 384x288 only. With those resolutions the accuracy should be higher.

**Comment by murdockhou** [comment]
Thanks for your reply, got it!
