### ISSUE TITLE
Embedding STN network like Alphapose

### ISSUE THREAD

**Issue by murdockhou** [stefanopini/simple-HRNet#17]
Hi, 

I have used hrnet model on real-live video and find that the keypoint of same person jitter seriously. The alphapose paper have said that they add STN network before pose-estimation network and SDTN network after pose-estimation network, the reason that they do this is they found that slightly difference of one same person box can make great influence on pose-estimation. So, how do you think of this? Could make the pose result more stable by adding STN and SDTN as alphapose does?

Thanks.

**Comment by stefanopini** [comment]
Hi,
Thank you for the suggestion!
I rapidly checked the alphapose repo and papers and I think that the STN/SDTN module had been used in the first version of the architecture, but it was removed afterwords.
Can you double-check it?

By the way, I think that a tracking functionality and a smooth update of the bounding boxes could heavily improve the visual quality of the pose estimations.

**Comment by murdockhou** [comment]
Hi，
Thank you for reply!

You are right, they pushed STN/SDTN module in their RMPE paper and torch version, but removed in their published Pytorch/Mxnet version. So I'm a little confused about the real performacne about STN/SDTN module because their Pytorch version works well, i mean the joint jitter is much less than Yolo v3 + HRNet does. So i want to find a solution to reduce joint jitter and make pose estimation much more stabel on visual looks. 

Hope that you can add a better visual quality of the pose estimations in your repo and i will try to add STD/SDTN in real-work to find if it is useful or not.

**Comment by stefanopini** [comment]
Hi @murdockhou ,

I've added a simple method for person tracking and joint temporal smoothing (that should slightly reduce jittering) in the script `live-demo.py`.

Have you found any solution to reduce joint jitter and obtain visually nicer skeletons?

**Comment by murdockhou** [comment]
@stefanopini I treat each person joints as a var and used kalman filter for smoothing. This can reduce jittering but when people moves fast it will casue worse visualization.
