### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by murdockhou** [stefanopini/simple-HRNet#18]
Hi, 
I find somewhere maybe cause error in repo, [here](https://github.com/stefanopini/simple-HRNet/blob/master/misc/visualization.py#L142), sometimes this will cause error like that:

`AttributeError: 'cv2.UMat' object has no attribute 'shape'`

Maybe do not return after `cv2.line` is better. This error did not shown as before but occured today when i use it, so please check it.

**Comment by stefanopini** [comment]
Are you reading a video file or a webcam?
Have you deactivated vidgear?

**Comment by murdockhou** [comment]
It's a little stranger, i try use ori code but no error occured, but i'm sure that i have met this error before, so weired.
