### ISSUE TITLE
Running on windows  ?

### ISSUE THREAD

**Issue by tonoim** [stefanopini/simple-HRNet#2]
Hi Stefano , thanks for the ease of use code , is it possible to run the code in windows ? And i guess it requires CUDA toolkit to run ? I tried a to port a similar `hrnet` implementation to run in windows but i could not manage it as such . Sadly `wsl` does not really support CUDA access in windows

**Comment by stefanopini** [comment]
Hi @tonoim !

I've just tried the code on a pc with Windows 10 and CUDA 10 and it works.
I've also tested it with the option `--device cpu` (that should be the default if CUDA is not detected) and it still works (very slowly).

Could you post your system/environment information?
