### ISSUE TITLE
ModuleNotFoundError: No module named 'cpu_nms'

### ISSUE THREAD

**Issue by lfxx** [stefanopini/simple-HRNet#22]
When i ran datasets/COCO.py,this error appears.Any suggestions?

**Comment by lfxx** [comment]
Has Solved it.Close this issue

**Comment by chengxianda54321** [comment]
how to solve this question?

**Comment by stefanopini** [comment]
@lfxx Could you report how you solved this error?

**Comment by lfxx** [comment]
> @lfxx Could you report how you solved this error?

Yeah,since cython file needs to be built.We need a MAKEFILE file to build it:

[Makefile.txt](https://github.com/stefanopini/simple-HRNet/files/3629303/Makefile.txt)
When use this,delete .txt!Hope this can help you~

**Comment by lfxx** [comment]
> how to solve this question?

Sorry for the late reply.The answer is posted,let me know if it works!

**Comment by stefanopini** [comment]
Thank you! I have updated the `README.md` and added the missing `Makefile`.

**Comment by BonJovi1** [comment]
This error may also show up if the `.so` file generated is not in `PYTHONPATH`. I solved this by adding the nms directory directly to the path:
```
export PYTHONPATH=$PYTHONPATH:<path-to-simple-HRNet>/misc/nms 
```
One can try this in case the error still shows up.

**Comment by stefanopini** [comment]
@BonJovi1 Thank you for the hint! I've added a note in the `README.md`
