### ISSUE TITLE
Import Error with numpy 1.16.5

### ISSUE THREAD

**Issue by timtensor** [stefanopini/simple-HRNet#25]
Hi Stefano 
I am currently getting the following error while running the live demo script for a saved video. I was wondering if you had faced such an issue ?  python3.6 

```
ImportError: numpy.core.multiarray failed to import
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 12, in <module>
    import subprocess, tempfile, os.path, re, pwd, grp, os, time
  File "/usr/lib/python3.6/tempfile.py", line 184, in <module>
    from random import Random as _Random
ImportError: cannot import name 'Random'

Original exception was:
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "scripts/live-demo.py", line 5, in <module>
    import cv2
  File "/home/timtensor/.local/lib/python3.6/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 12, in <module>
    import subprocess, tempfile, os.path, re, pwd, grp, os, time
  File "/usr/lib/python3.6/tempfile.py", line 184, in <module>
    from random import Random as _Random
ImportError: cannot import name 'Random'

Original exception was:
Traceback (most recent call last):
  File "scripts/live-demo.py", line 5, in <module>
    import cv2
  File "/home/timtensor/.local/lib/python3.6/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import

```

**Comment by timtensor** [comment]
I tried by running it on vitual enviroment with python 3.6 and had the same issue . It seems to be some kind of issues with the numpy package

**Comment by stefanopini** [comment]
Hi!
It seems an error involving numpy and opencv...
Can you try to run the command `pip install --user numpy` and see if it solves the issue?

**Comment by timtensor** [comment]
Hi @stefanopini , i did try using `pip install .-U numpy` but the error still persisted. It just updated the numpy version to a newer version .

**Comment by stefanopini** [comment]
Ok, can you try to re-install also opencv then?
Try using the command `pip install -U opencv-python`

**Comment by timtensor** [comment]
Hello @stefanopini i tried both of the methods, also uninstalling and installing it . As mentioned by you long time ago , I am using a python virtual enviroment (python3.6) . Are you using the same kind of setup ?

**Comment by stefanopini** [comment]
I have numpy 1.16.1 and opencv 3.4.5 in a conda environment. In the next days, I'll try with a fresh virtual environment.

In the meantime, can you run the following code and post the output?
`python -c "import cv2; print(cv2.__version__, cv2.__file__)"`
`python -c "import numpy; print(numpy.__version__, numpy.__file__)"`

**Comment by timtensor** [comment]
Sure , here are my outputs 

```
(posefit) timt:~/sandbox/test$ python -c "import cv2; print(cv2.__version__, cv2.__file__)"
4.1.1 /home/timt/sandbox/test/posefit/lib/python3.6/site-packages/cv2/cv2.cpython-36m-x86_64-linux-gnu.so
(posefit) timt:~/sandbox/test$ python -c "import numpy; print(numpy.__version__, numpy.__file__)"
1.17.2 /home/timt/sandbox/test/posefit/lib/python3.6/site-packages/numpy/__init__.py

```

**Comment by stefanopini** [comment]
Hi @timtensor 

In the error you reported, opencv is loaded from the user local packages
`/home/timtensor/.local/lib/python3.6/site-packages/cv2/`
and it doesn't work.

In your last comment opencv is loaded from the virtual environment `posefit`
`/home/timt/sandbox/test/posefit/lib/python3.6/site-packages/cv2/`
and it works (you were able to print the opencv version).

Can you check if the `live-demo` script works using the virtual environment `posefit`?

**Comment by timtensor** [comment]
Hi @stefanopini thank you for pointing out , i did a reinstall of my virtual enviroment and it worked just fine. Thank you for your suppport .
