### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by guancheng817** [stefanopini/simple-HRNet#27]
hi, thanks for your works. The problem I met is that when I run the following in command line, it could run successfully.
###
python ./tools/live_demo.py --camera 0 
###
However, when I run in pycharm, i appear the following errors:
Traceback (most recent call last):
  File "/mnt/simple-HRNet/scripts/sit_ups.py", line 12, in <module>
    from SimpleHRNet import SimpleHRNet
  File "/mnt/simple-HRNet/SimpleHRNet.py", line 7, in <module>
    from models.detectors.YOLOv3 import YOLOv3
  File "/mnt/simple-HRNet/models/detectors/YOLOv3.py", line 12, in <module>
    from .yolo.models import Darknet
  File "/mnt/simple-HRNet/models/detectors/yolo/models.py", line 10, in <module>
    from utils.parse_config import *
ModuleNotFoundError: No module named 'utils'

could you tell me how to solve this problem, thanks a lot.

**Comment by stefanopini** [comment]
Sure!

PyCharm runs the script from the script folder (`/mnt/simple-HRNet/scripts/`), while the script needs to be run from the project folder (`/mnt/simple-HRNet/`) as you do when you use the command line.

You just have to:

- open Run > Edit configurations...
- Select the script file you want to run
- Change the working directory from `/mnt/simple-HRNet/scripts` to `/mnt/simple-HRNet`
- Apply changes
