### ISSUE TITLE
Import error , no module named SimpleHrnet 

### ISSUE THREAD

**Issue by timtensor** [stefanopini/simple-HRNet#3]
Hi  @stefanopini i seem to unable to import the `simple Hrnet` module . I have the following error 
I was wondering , if i have missed some steps or additional confguration . I am running on a virtual machine with ubuntu 16.04
```
Traceback (most recent call last):
  File "scripts/live-demo.py", line 6, in <module>
    from SimpleHRNet import SimpleHRNet
ImportError: No module named SimpleHRNet
```

My directory structure is similar to yours 
```
── datasets
│   ├── COCO.py
│   └── LiveCamera.py
├── LICENSE
├── misc
│   └── utils.py
├── models
│   ├── detectors
│   │   ├── yolo
│   │   │   ├── assets
│   │   │   │   ├── dog.png
│   │   │   │   ├── giraffe.png
│   │   │   │   ├── messi.png
│   │   │   │   └── traffic.png
│   │   │   ├── config
│   │   │   │   ├── coco.data
│   │   │   │   ├── create_custom_model.sh
│   │   │   │   ├── custom.data
│   │   │   │   ├── yolov3.cfg
│   │   │   │   └── yolov3-tiny.cfg
│   │   │   ├── data
│   │   │   │   ├── coco.names
│   │   │   │   ├── custom
│   │   │   │   │   ├── classes.names
│   │   │   │   │   ├── images
│   │   │   │   │   │   └── train.jpg
│   │   │   │   │   ├── labels
│   │   │   │   │   │   └── train.txt
│   │   │   │   │   ├── train.txt
│   │   │   │   │   └── valid.txt
│   │   │   │   ├── get_coco_dataset.sh
│   │   │   │   └── samples
│   │   │   │       ├── dog.jpg
│   │   │   │       ├── eagle.jpg
│   │   │   │       ├── field.jpg
│   │   │   │       ├── giraffe.jpg
│   │   │   │       ├── herd_of_horses.jpg
│   │   │   │       ├── messi.jpg
│   │   │   │       ├── person.jpg
│   │   │   │       ├── room.jpg
│   │   │   │       └── street.jpg
│   │   │   ├── detect.py
│   │   │   ├── LICENSE
│   │   │   ├── models.py
│   │   │   ├── README.md
│   │   │   ├── requirements.txt
│   │   │   ├── test.py
│   │   │   ├── train.py
│   │   │   ├── utils
│   │   │   │   ├── augmentations.py
│   │   │   │   ├── datasets.py
│   │   │   │   ├── __init__.py
│   │   │   │   ├── logger.py
│   │   │   │   ├── parse_config.py
│   │   │   │   └── utils.py
│   │   │   └── weights
│   │   │       ├── darknet53.conv.74
│   │   │       ├── download_weights.sh
│   │   │       ├── yolov3-tiny.weights
│   │   │       └── yolov3.weights
│   │   └── YOLOv3.py
│   ├── hrnet.py
│   └── modules.py
├── README.md
├── requirements.txt
├── scripts
│   └── live-demo.py
├── SimpleHRNet.py
├── SimpleHRNet.pyc
├── weights
│   └── pose_hrnet_w48_384x288.pth
└── workout_mod.mp4
```

**Comment by stefanopini** [comment]
Hi! To import the `simpleHRNet` module, you need to have the project root path (i.e. the directory with the file `SimpleHRNet.py`) in your "python path" (i.e. the path in which python search the packages).
By default, the working directory is automatically added to your "python path" so it should work if you run the script from the project root with the command `python scripts/live-demo.py` .

On Linux, you can check it running the command `python -c "import sys;print(sys.path)"`: you should find your working directory in the printed list. (On Windows, the working directory is represented with an empty string.)
If you don't find it, just add the project root path to the environment variable `PYTHONPATH`.

**Comment by timtensor** [comment]
Hi  Ok i think i understand you . I did a print out of the system configuration which i do have the root folder 
`['', '/home/pm', '/home/pm/pf/simple-HRNet', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/pm/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/local/lib/python2.7/dist-packages/pyOpenSSL-19.0.0-py2.7.egg', '/usr/lib/python2.7/dist-packages']
`
However i have two versions of python , `python3.5` and `python2.7` . Do you think it interferes ??

**Comment by stefanopini** [comment]
Yes, it could because I didn't test the script on python 2.7... You should use python 3.
Can you try to run the software using `python3 scripts/live-demo.py`?
In any case, I suggest you to use a virtual environment (see https://docs.python.org/3.7/tutorial/venv.html).

**Comment by timtensor** [comment]
Hi @stefanopini , as you suggested i created a virtua enviroment . I see an error from the `yolo` model and running on `python3.6`
The error is as follows 
Traceback (most recent call last):
```
  File "<stdin>", line 1, in <module>
  File "/home/test/simple-HRNet/SimpleHRNet.py", line 6, in <module>
    from models.detectors.YOLOv3 import YOLOv3
  File "/home/test/simple-HRNet/models/detectors/YOLOv3.py", line 7, in <module>
    from .yolo.models import Darknet
  File "/home/test/simple-HRNet/models/detectors/yolo/models.py", line 9, in <module>
    from utils.parse_config import *
ModuleNotFoundError: No module named 'utils'
```
the output of the sys path is as follows 

`'/home/test/simple-HRNet', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/home/test/simple-HRNet/simpleHrnet/lib/python3.6/site-packages']`

**Comment by stefanopini** [comment]
You're right, there was a bug on the yolo import... I should have just fixed it.
Let me know if it works now.

**Comment by timtensor** [comment]
Hi @stefanopini ,  I still have  `import error` with No module named `SimpleHRNet` . As you suggested i create a virtual env and followed the steps as mentioned in the readme. I did as follows 
a) Created virtual env `hrnet` with the following `python3.6 -m venv hrnet`
b) Activated the python virtual env `source hrnet/bin/activate`
c) Installed the requirements and dependencies `pip install -r requirements.txt`
d) Clone `yolo` and installed dependencies there and created a folder `weights` for the pretrained model 
e) Executed the command `python scripts/live-demo.py --camera_id 0` Which lead to the error 

```
`Traceback (most recent call last):
  File "scripts/live-demo.py", line 7, in <module>
    from SimpleHRNet import SimpleHRNet
ModuleNotFoundError: No module named 'SimpleHRNet`
```
f) checking for the python path using `python -c "import sys;print(sys.path)"`
I do see the Hrnet module included in the system path 
`
['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/test/simple-HRNet/hrnet/lib/python3.6/site-packages']`

I am not really sure what could be the issue . OS is Ubuntu 18

**Comment by timtensor** [comment]
@stefanopini finally i managed to run the script but modying the `sys path ` in the file ``/live-demo.py ` . 
```
import sys 
sys.path.append("/home/test/simple-HRNet")
```
Maybe it is a dirty solution but seems to work . 
and running the following , I still need to specify the `--weights` flag . However , when  i run it , in a CUDA enabled device , i still get `CUDA 0`  and was wondering how can i get the `venv` access the CUDA. Do i have to install the CUDA toolkit for the `venv` ?? And did you have some ideas as in how to optimzie the detections ??

**Comment by stefanopini** [comment]
Dear @timtensor , I've finally been able to reproduce the error and fix it. It was related to different `sys.path` initialization between anaconda and non-anaconda environments.
Thank you for sharing your code. Indeed, my workaround is similar to yours, but it works regardless of the path of the project.

Regarding CUDA, you just need to install pytorch with CUDA support. If the script outputs `cuda:0`, it means that the GPU 0 (with CUDA support) is used to execute the network.
If you need further support, please open a specific issue (e.g. "frame rate is very low").
