### ISSUE TITLE
Possibiltity to save the overlaid images into a video stream?

### ISSUE THREAD

**Issue by basicvisual** [stefanopini/simple-HRNet#32]
Hi , i see the overlaid images are saved in the following 
https://github.com/stefanopini/simple-HRNet/blob/master/scripts/live-demo.py#L77

I was wondering if it is possile to save  the overlaid images as a video stream as output ?

**Comment by stefanopini** [comment]
Option added!
Update the repository to the latest commit and use the `--save_video option`.
