### ISSUE TITLE
KeyError: "param 'initial_lr' is not specified

### ISSUE THREAD

**Issue by gillmac13** [stefanopini/simple-HRNet#33]
@stefanopini 
Thanks for making available this user-friendly version of deep HRNet!

I am trying to retrain a pre-trained model (the idea is to augment to coco dataset with my own data) and run into this problem:

`(myenv) gilles@gilles-N55SF:~/mywork/gilles_hrnet$ python3 scripts/train_coco.py -p ./weights/pose_hrnet_w48_384x288.pth -e 200

cuda:0
Starting experiment `20191107_1858` @ 2019-11-07 18:58:36
Loading train and validation datasets...
loading annotations into memory...
Done (t=4.22s)
creating index...
index created!
100%|█████████████████████████████████| 118287/118287 [00:43<00:00, 2717.40it/s]

COCO dataset loaded!
loading annotations into memory...
Done (t=0.13s)
creating index...
index created!
100%|█████████████████████████████████████| 5000/5000 [00:01<00:00, 2704.04it/s]

COCO dataset loaded!
cuda:0
Traceback (most recent call last):
  File "scripts/train_coco.py", line 153, in <module>
    main(**args.__dict__)
  File "scripts/train_coco.py", line 108, in main
    device=device
  File "/home/gilles/mywork/gilles_hrnet/training/COCO.py", line 119, in __init__
    device=device
  File "/home/gilles/mywork/gilles_hrnet/training/Train.py", line 201, in __init__
    last_epoch=self.starting_epoch)
  File "/home/gilles/myenv/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 245, in __init__
    super(MultiStepLR, self).__init__(optimizer, last_epoch)
  File "/home/gilles/myenv/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 26, in __init__
    "in param_groups[{}] when resuming an optimizer".format(i))
KeyError: "param 'initial_lr' is not specified in param_groups[0] when resuming an optimizer"
`
I understand that the training script is expecting an initial_lr, but I'd appreciate if you could help me find the best way to pass it.

**Comment by stefanopini** [comment]
Hi!
Try to update the code to the latest commit, I should have fixed a bug related to the lr sheduler.
Please reopen the issue if the error persists.

**Comment by gillmac13** [comment]
It works perfectly now.
Thanks!
