### ISSUE TITLE
Adding multi-camera

### ISSUE THREAD

**Issue by lan786** [stefanopini/simple-HRNet#34]
@stefanopini  Hi, how we can add more than one camera (2 or 3) in this project? No matter how many output screens (2 or 3) or no any need of calibration. Just simple input 2 or 3 cameras and then estimate poses on cameras separately. Simple OpenCV code is working fine for 2 cameras but I want to apply using threading as given below.
I want to add this code in your scripts/live-demo.py camera reading code

    import cv2
    import threading
    class camThread(threading.Thread):
        def __init__(self, previewName, camID):
            threading.Thread.__init__(self)
            self.previewName = previewName
            self.camID = camID
        def run(self):
            print ("Starting " + self.previewName)
            camPreview(self.previewName, self.camID)
    def camPreview(previewName, camID):
        cv2.namedWindow(previewName)
        cam = cv2.VideoCapture(camID)
        if cam.isOpened():
            rval, frame = cam.read()
        else:
            rval = False
        while rval:
            cv2.imshow(previewName, frame)
            rval, frame = cam.read()
            key = cv2.waitKey(20)
            if key == 27:  
                break
        cv2.destroyWindow(previewName)
    thread1 = camThread("Camera 1", 0)
    thread2 = camThread("Camera 2", 1)
    thread1.start()
    thread2.start()

Or you can add your own simple code for dual camera.
Looking for your kind suggestions.
Thanks

**Comment by stefanopini** [comment]
Hi!

I think that, to analyze the input from multiple cameras using threads, you need to handle the concurrent access to another thread that performs the network inference on GPU (it could be implemented with queues).
Alternatively, you can create an object of the class SimpleHRNet in each thread (each of these will load a different instance of the network, potentially on two different GPUs) and use that to predict the pose independently. This approach is less efficient but quite more simple.

Let me know if it works!
