### ISSUE TITLE
Adding a check for flipped videos ?

### ISSUE THREAD

**Issue by timtensor** [stefanopini/simple-HRNet#35]
Hi while working on one of the videos, i realized that the input videos was upside down and thus it failed to detect any 2D keypoints. Is there a way in opencv or otherwise to add an check for it ? Is it even possible

**Comment by stefanopini** [comment]
As far as I know, it isn't possible with opencv, but maybe you could read metadata information with other packages.
Alternatively, you could perform inference with both vertical and rotated images and use both the detections.

**Comment by timtensor** [comment]
Thanks , i realized a lot smartphones do this rotation and opencv cannot really do it on the fly. I found the following in 
[flipped videos](https://stackoverflow.com/questions/53097092/frame-from-video-is-upside-down-after-extracting) I guess it can be added in `live-demo.py` file ?

**Comment by stefanopini** [comment]
Yes, thank you for the suggestion.
I think it should be added as an option because it requires additional packages (ffmpeg and/or other libraries).

**Comment by timtensor** [comment]
I see, thanks ! i wonder what would be the best way to add , according to your suggestion .

**Comment by stefanopini** [comment]
Hi, I've just added it!
Please check out the latest [commit](https://github.com/stefanopini/simple-HRNet/commit/08c35047f5f6b7dbc9dd41fd4f16581fe433c9c6) and let me know if it works :-)
