### ISSUE TITLE
Have you trained pose-hrnet from imagenet pretrained model ?

### ISSUE THREAD

**Issue by mitumao-DD** [stefanopini/simple-HRNet#37]
I want to train pose-hrnet from imagenet pretrained model, but l only have one Titan XP GUP , so I want to know how much time it will consume ? Thanks！

**Comment by stefanopini** [comment]
According to old tests I did, it should require 1 to 2 hours per epoch for training on COCO (speed depends also on your storage speed). Please note that official weights are the result of training for 210 epochs.
I suggest you to train the model for a couple of epochs and then estimate the time-for-epoch on your machine.
