### ISSUE TITLE
[Question] GUI interface and change in Vizualization 

### ISSUE THREAD

**Issue by ns3new** [stefanopini/simple-HRNet#38]
Hi , I was wondering , if one can make a GUI , perhaps for example , to show the angles of rotation between the joints. For now one can show it using open CV `cv2.put2text` format. I was wondering what packages to use ? 

Second , is it possible to have different color codes of the lines joining the keypoints ? If so how and where can one make such changes ?

Thanks in advance

**Comment by stefanopini** [comment]
1) I think opencv is the simpler package to do that. Another option is to use PIL to write text on the image (visual results are more pleasant than those of opencv). To make a GUI, you can have a look at Qt.
2) Yes! You can change skeleton (and point) color palette using the argument(s) `skeleton_color_palette` (and `points_color_palette`) of the function [`draw_points_and_skeleton`](https://github.com/stefanopini/simple-HRNet/blob/master/misc/visualization.py#L151). Only [matplotlib color palettes](https://matplotlib.org/devdocs/tutorials/colors/colormaps.html) are supported.
