### ISSUE TITLE
ModuleNotFoundError: No module named 'models.detectors.yolo.models'

### ISSUE THREAD

**Issue by Jichen66** [stefanopini/simple-HRNet#39]
Hi,

 I met a problem when I run 'python scripts/live-demo.py --camera_id 0', it said that 'ModuleNotFoundError: No module named 'models.detectors.yolo.models'. Does anyone have idea how to solve this problem?

Btw, I have installed all those things in the requirments.txt and my system is Win10

Many thanks in advance!

**Comment by stefanopini** [comment]
Are you interested in multi-person support?

- No:
Add the option --single_person

- Yes:
Have you followed the instructions for multi-person support?
> - For multi-person support:
>     - Get YOLOv3:
>         - Clone [YOLOv3](https://github.com/eriklindernoren/PyTorch-YOLOv3/tree/47b7c912877ca69db35b8af3a38d6522681b3bb3) 
> in the folder ``./models/detectors`` and change the folder name from ``PyTorch-YOLOv3`` to ``yolo``  
>           OR
>         - Update git submodules  
>         ``git submodule update --init --recursive``
>     - Install YOLOv3 required packages  
>        ``pip install -r requirements.txt`` (from folder `./models/detectors/yolo`)
>     - Download the pre-trained weights running the script ``download_weights.sh`` from the ``weights`` folder

**Comment by Tony-Yan2018** [comment]
> Hi!
> Are you interested in multi-person support?
> 
> * No:
>   Add the option --single_person
> * Yes:
>   Have you followed the instructions for multi-person support?
> 
> > * For multi-person support:
> >   
> >   * Get YOLOv3:
> >     
> >     * Clone [YOLOv3](https://github.com/eriklindernoren/PyTorch-YOLOv3/tree/47b7c912877ca69db35b8af3a38d6522681b3bb3)
> >       in the folder `./models/detectors` and change the folder name from `PyTorch-YOLOv3` to `yolo`
> >       OR
> >     * Update git submodules
> >       `git submodule update --init --recursive`
> >   * Install YOLOv3 required packages
> >     `pip install -r requirements.txt` (from folder `./models/detectors/yolo`)
> >   * Download the pre-trained weights running the script `download_weights.sh` from the `weights` folder



if you added --single_person option but still got the error, just comment out the 2 lines: `from models.poseresnet import PoseResNet
from models.detectors.YOLOv3 import YOLOv3` in file SimpleHRNet.py

**Comment by stefanopini** [comment]
Thank you @Tony-Yan2018 for reporting this!
I've updated the code accordingly.
