### ISSUE TITLE
L2 normalization of keypoints per frame ?

### ISSUE THREAD

**Issue by basicvisual** [stefanopini/simple-HRNet#40]
Hi i am trying to do normalization of keypoints for post processing. On looking through the code it seems like one needs to first extract `x,y` cordinates . For a single person it seems to work ok . 
Pseudo code 

```

vec = np.empty(pts.shape[1] * 2)
vec[0::2] = pts[:,:,0]
vec[1::2] = pts[:,:,1]
print(vec)

norm = np.linalg.norm(vec)
```
Could this be the right way to do it ? This method only works for single person detection . Do you perhaps have a better suggesiton ?

**Comment by stefanopini** [comment]
Hi!

Regarding the multi-person case, you can scale (and resize) each pose using the coordinates of each bounding box (such as subtracting minimum x and y of the bounding box and dividing by its width and height).

Regarding the keypoint normalization, you can normalize w.r.t. the whole vector (as you reported) or normalize the x and y axes independently.

To get the person bounding boxes, set `return_bounding_boxes=True` when `SimpleHRNet` is initialized.
