### ISSUE TITLE
 New Pillow version (7.0.0) breaks torchvision (ImportError: cannot import name 'PILLOW_VERSION' from 'PIL') #1712 

### ISSUE THREAD

**Issue by timtensor** [stefanopini/simple-HRNet#42]
A quick heads up , there seems to be problem with the new Pillow version. Alternate solution is here 

https://github.com/pytorch/vision/issues/1712

**Comment by hugovk** [comment]
[torchvision v0.5.0](https://github.com/pytorch/vision/releases/tag/v0.5.0) has been released with the fix:

1. Require `torchvision>=0.5.0`
2. If Pillow was temporarily pinned, remove the pin

**Comment by stefanopini** [comment]
Great! Requirements updated.
