### ISSUE TITLE
Question about pre-trained weight

### ISSUE THREAD

**Issue by happyyqt** [stefanopini/simple-HRNet#44]
Hi, 

Thank you for your excellent work which is a huge help for beginners. I have a question about how to find the official pre-trained weights from the link you gave. Looking forward to your reply. : )

**Comment by stefanopini** [comment]
Hi!
I've just updated the [installation instructions](https://github.com/stefanopini/simple-HRNet#installation-instructions) including direct download links for the official pre-trained weights.
