### ISSUE TITLE
Decoding our model output?

### ISSUE THREAD

**Issue by muellerzr** [stefanopini/simple-HRNet#45]
Hi! First, I love the work you have been doing. I'm working on implementing a pipeline for these heatmap-based pose problems in the fast.ai framework at the moment and I had a quick question! So I understand we are encoding our y's into `n` heatmaps that have a size of 1/2 our image size. How do we then grab the coordinates from these generated heatmaps? I'm a bit lost on the math from this :/ I think we need the bounding boxes for this? I'm having a little difficulty putting it all together. Any help would be **greatly** appreciated!

Thank you!

Zach

**Comment by muellerzr** [comment]
Nevermind, found this in the keypoints script. Thank you :)

**Comment by stefanopini** [comment]
If you have other questions, feel free to ask 🙂
