### ISSUE TITLE
Simple Baselines Compatibility

### ISSUE THREAD

**Issue by gadese** [stefanopini/simple-HRNet#46]
Hi!

Is this also compatible with the Simple Baselines models provided in the original HRNet repository? (for example, pose_resnet_50_256x192.pth)

Thank you

**Comment by stefanopini** [comment]
Hi!

At the moment no, only the HRNet model is supported.
However, it should be quite easy to add the support to the resnet model, so I'm planning to do it in the future (even if the priority now is to add the support to the new Higher HRNet).

I'll keep you updated.

**Comment by stefanopini** [comment]
Hi @gadese 

I've just added the support to the Simple Baselines models!
Please have a look at the new parameters ``model_name`` (in the SimpleHRNet class) and ``--hrnet_m`` (in scripts).

Feel free to re-open the issue if you find any bug 🙂
