### ISSUE TITLE
Train on other dataset

### ISSUE THREAD

**Issue by carolchenyx** [stefanopini/simple-HRNet#47]
Thanks for your excellent work. If I want to train on my own dataset, how can I do? Thanks.

**Comment by stefanopini** [comment]
Hi! To train on your own dataset, you just have to create a new class in `datasets/` which inherits the class [`HumanPoseEstimation`](https://github.com/stefanopini/simple-HRNet/blob/master/datasets/HumanPoseEstimation.py).

You have to implement the standard methods of the pytorch class `Dataset` and the additional method `evaluate_accuracy(self, output, target, params=None)`. You can use the `COCO` dataset as a reference.

Let me know if you have any other question and, if you're working on a public dataset, feel free to send a pull request with the new dataset class! I'll be glad to add it in this repository
