### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by hundanLi** [stefanopini/simple-HRNet#48]
How about the inference speed on cpu, please?

**Comment by stefanopini** [comment]
Hi!

Inference speed highly depends on the hardware and on the settings (`32` or `48` channels, `256x192` or `384x288`, single- or multi-person, with or without tracking, etc.) so I suggest you to download the code and try the preferred setting on your device.

For instance, on a desktop with an Intel i7-5820K and on a laptop with an Intel i7-1065G7, it runs at between 0.2 and 5 fps depending on the settings.
It runs at ~2 fps using `COCO w32 256x192` (weights `pose_hrnet_w32_256x192.pth`) in `single_person`.
