### ISSUE TITLE
Will this run with pytorch cpu?

### ISSUE THREAD

**Issue by bpeck81** [stefanopini/simple-HRNet#5]
I'm wondering if I can run this code on machines without a gpu and just with the cpu version of pytorch.

**Comment by bpeck81** [comment]
I got it to work. The only change necessary was this line in SimpleHRNet.py:
`        self.model.load_state_dict(torch.load(checkpoint_path, map_location=device))
`
where I added map_location=device.

**Comment by stefanopini** [comment]
Thank you, I've just fixed that.
