### ISSUE TITLE
Install Problem: Make Error

### ISSUE THREAD

**Issue by wlsh1up** [stefanopini/simple-HRNet#53]
Thank you for your reproduce.  
When I follow Installation instructions to **cd misc; make**,  I encounter errors.   

> cd nms; python setup_linux.py build_ext --inplace; rm -rf build; cd ../
running build_ext
skipping 'cpu_nms.c' Cython extension (up-to-date)
skipping 'gpu_nms.cpp' Cython extension (up-to-date)

How to solve it?  Great Thanks!

**Comment by stefanopini** [comment]
From what you reported

> ```
> skipping 'cpu_nms.c' Cython extension (up-to-date)
> skipping 'gpu_nms.cpp' Cython extension (up-to-date)
> ```

it looks like you have already compiled it.
Can you check if it works?

Otherwise, try to run (in the folder `misc` )
`make clean`
then again
`make`

Let me know if this solves the issue.

**Comment by wlsh1up** [comment]
I am sorry for the late reply. The problem has been solved

Absolute path should be used in **misc/nms/nms.py**
> from misc.nms.cpu_nms import cpu_nms
> from misc.nms.gpu_nms import gpu_nms

Unimportant changes as follows
> find misc/nms -name '*.so' -delete
> -arch=sm_70  // My GPU: 2080ti

Thanks again for your reproduce.
