### ISSUE TITLE
Where can I get the heatmaps generated? I followed the instructions and got joints output. But where's the heatmap?

### ISSUE THREAD

**Issue by imharshitagrawal** [stefanopini/simple-HRNet#54]

**Comment by stefanopini** [comment]
Hi!

At the moment, there is not an option to get the heatmaps from the predict function.
However, you can see that heatmaps are obtained in the following lines:

- https://github.com/stefanopini/simple-HRNet/blob/master/SimpleHRNet.py#L232 (single person)
- https://github.com/stefanopini/simple-HRNet/blob/master/SimpleHRNet.py#L333 (multi person)

You can return that tensor/ndarray and use it elsewhere.

I'll add an option `return_heatmaps` to the `SimpleHRNet` class in the future.

**Comment by stefanopini** [comment]
Done!
Please look at the README
