### ISSUE TITLE
typo in Train.py

### ISSUE THREAD

**Issue by N1M49** [stefanopini/simple-HRNet#59]
I believe these two lines should be changed to val?

https://github.com/stefanopini/simple-HRNet/blob/06f6e350c64af6f62c16a181b69d22ce342e4036/training/Train.py#L290-L291

**Comment by N1M49** [comment]
Also in the lines below, shouldn't the evaluation be on the validation dataset? 

https://github.com/stefanopini/simple-HRNet/blob/06f6e350c64af6f62c16a181b69d22ce342e4036/training/Train.py#L285-L288

**Comment by stefanopini** [comment]
Definitely, thank you for spotting them!

Using the [COCOTrain class](https://github.com/stefanopini/simple-HRNet/blob/06f6e350c64af6f62c16a181b69d22ce342e4036/training/COCO.py) and other custom classes, where there aren't these typos, I've never spotted them.
