### ISSUE TITLE
ModuleNotFoundError: No module named 'cpu_nms'

### ISSUE THREAD

**Issue by john2choi** [stefanopini/simple-HRNet#60]
Hi i got this error from nms.py while i'm running scripts/train_coco.py

i tried this but, same with problem.
>If you want to run the training script on COCO scripts/train_coco.py, you have to build the nms module first.
Please note that a linux machine with CUDA is currently required. Built it with either:
cd misc; make or
cd misc/nms; python setup_linux.py build_ext --inplace

result:
>/misc$ make
cd nms; python setup_linux.py build_ext --inplace; rm -rf build; cd ../../
running build_ext
skipping 'cpu_nms.c' Cython extension (up-to-date)
skipping 'gpu_nms.cpp' Cython extension (up-to-date)

my situations below:
on ubuntu 18.04
anaconda3
Python 3.6
Pytorch 10.0.0 

thanks.

**Comment by stefanopini** [comment]
Hi! Sorry for the late reply.

I've just updated the `README.md` file with this suggestion [https://github.com/stefanopini/simple-HRNet/issues/22#issuecomment-666068753](https://github.com/stefanopini/simple-HRNet/issues/22#issuecomment-666068753) .
Let me know if it works.
