### ISSUE TITLE
Custom Dataset without Bounding Boxes

### ISSUE THREAD

**Issue by aakashcurefit** [stefanopini/simple-HRNet#61]
Hi, @stefanopini Thanks for this implementation. 

Q1. I want to train using a custom 14 key point dataset. The dataset contains the ground truth key points for the images, but not the ground truth "bbox" entities. I am using yolov3 to get the bounding boxes. Why there is a need to set the "joints" here as NULL? ->

https://github.com/stefanopini/simple-HRNet/blob/master/datasets/COCO.py#L134

Q2. How about using the ground truth key points for creating the Bounding Box? 

Waiting in Anticipation.
Thanks!!

**Comment by stefanopini** [comment]
Hi @aakashcurefit ,

As far as I remember, that line is used only for testing, in particular for predicting the keypoints on the COCO test set (whose ground truth is not publicly available).
For a custom dataset, you definitely need to set the ground truth joints for the dataset samples.

If you use the bounding boxes predicted by yolov3, you have to update your joints accordingly to the predicted bounding box of each subject.
As an alternative, you can train the network without extracting the bounding boxes (i.e. using the entire image as input) if the main content of the image is the subject of interest.
