### ISSUE TITLE
A small Bug

### ISSUE THREAD

**Issue by aakashcurefit** [stefanopini/simple-HRNet#62]
Hi, 

Here -> https://github.com/stefanopini/simple-HRNet/blob/master/misc/utils.py#L243

This should be --
avg_acc = avg_acc / cnt if cnt != 0 else torch.tensor(0)

and in similar places.

Else, you will get an Attribute error as **avg_acc.item()** doesn't have an attribute .item() whenever this is function returns 0. 

Thanks!!

**Comment by stefanopini** [comment]
Thank you for catching it!
I've just fixed that in the latest commit.
