### ISSUE TITLE
How can I generate 2D keypoint json file from video 

### ISSUE THREAD

**Issue by christw16** [stefanopini/simple-HRNet#64]
Hi there~
Thank you for sharing this great work~

My question is how can I generate 2D keypoint json file from video when I run live-demo.py?
Thank you so much

**Comment by stefanopini** [comment]
Hi!

I haven't implemented such feature, but you can have a look at the script `extract-keypoints.py` that produces a csv file with all the predictions for an image or a video.

If you prefer json over csv, it should be easy to change it in that script.

If you need to view the predictions and save the keypoints in the meanwhile, you need to combine the two scripts `live-demo.py` (for the visualization) and extract-keypoints.py` (for the saving).

Let me know if you need further help.

**Comment by christw16** [comment]
@stefanopini  okay~ Looking forward to seeing your work concerning json format ~
