### ISSUE TITLE
What is the pose tracking method used in this simple-HRNet

### ISSUE THREAD

**Issue by christw16** [stefanopini/simple-HRNet#67]
Hi~ Thank you for sharing this awesome job

I wanna ask that what is the tracking method you add in simple-HRNet?
Because the original method and paper seems to be no tracking method in it?

Thank you~

**Comment by stefanopini** [comment]
Hi!

It is a trivial tracking by detection algorithm, defined here:
https://github.com/stefanopini/simple-HRNet/blob/f4a81742975f7a3fb85493a4ed197e21e93f7222/misc/utils.py#L382-L425

In short, it builds a similarity matrix between the previous and the current detections (based on bbox and pose similarity) then it associates previous and current detections with the Munkres algorithm to maximize the similarity of the associations.
