### ISSUE TITLE
no such file or directory:'ffprobe':'ffprobe'

### ISSUE THREAD

**Issue by FrankYoungchen** [stefanopini/simple-HRNet#69]
after pip install ffmpeg-python, when run live-demo.py, it will appear 
'FileNotFoundError:[Error 2] No such file or directory:' ffprobe':'ffprobe'

**Comment by FrankYoungchen** [comment]
how to solve the problem,bro~

**Comment by stefanopini** [comment]
As reported [here](https://github.com/kkroening/ffmpeg-python/issues/224), please make sure to have FFmpeg/FFprobe installed on your machine.
