### ISSUE TITLE
pose tracking using HRnet ?

### ISSUE THREAD

**Issue by basicvisual** [stefanopini/simple-HRNet#7]
Hi since , Hrnet has Yolov3 , enabled by default , is it possible to implement a tracking functionality as well ?

**Comment by stefanopini** [comment]
Yes it is, but I'm not planning to implement it in the near future.
By the way, contributions are welcome 🙂

**Comment by basicvisual** [comment]
@stefanopini thanks for the answer . Hopefully , soon :). I think the original authors have not implemented it either

**Comment by timtensor** [comment]
@basicvisual , there is some kind of implementation [here](https://github.com/lxy5513/hrnet/blob/master/pose_estimation/pose_track.py)  . Maybe it can be extended ?

**Comment by basicvisual** [comment]
Is there any progress or suggestions on this ?

**Comment by stefanopini** [comment]
I still didn't have the time to look at that, unfortunately.

**Comment by stefanopini** [comment]
Hi!
I've added a simple method for person tracking (and joint temporal smoothing) in the latest version of the script live-demo.py.

**Comment by basicvisual** [comment]
@stefanopini  thanks a ton !, Can i get bounding boxes if just enable the following flag ? 
                 return_bounding_boxes=True,  
Which i can see in the `live-demo.py` script .  

Another question, is that you have implemented , where one does not do frame by frame estimation of a video sequence.  How can activate that , for example . I want to a bunch of 12 frames and run prediction on that.  I think it is what is intended to do so right ?

**Comment by stefanopini** [comment]
> Can i get bounding boxes if just enable the following flag `return_bounding_boxes=True`?

Exactly.

> Another question, is that you have implemented , where one does not do frame by frame estimation of a video sequence. How can activate that , for example . I want to a bunch of 12 frames and run prediction on that.

You can simply call `model.predict(images)` where images is a batch of images and you'll receive in output a batch of predicted poses (and their bounding boxes if `return_bounding_boxes` is set to `True`).

**Comment by basicvisual** [comment]
Hi so if i understand it , this is only applicable to images right ? It does not work for i guess a saved video ? In the `model.predict(frame)` as stated below. Is it possible to not do prediction frame by frame but it batches of few ? Or perhaps i am confusing two different things 
`https://github.com/stefanopini/simple-HRNet/blob/be1b4467793845a55d6a6816fc745aa45670efd1/scripts/live-demo.py#L77`

**Comment by stefanopini** [comment]
The `live-demo.py` script is assumed to be run in real-time therefore the analysis is computed frame-by-frame.
However, once you have loaded a video, you can call `model.predict(batch_of_frames)` to get the prediction for a batch of frames.
