### ISSUE TITLE
Tiny Yolo

### ISSUE THREAD

**Issue by Tabriz12** [stefanopini/simple-HRNet#70]
First of all, thank you for your work.
I would like to know what are the performance gain and accuracy drop when using Tiny Yolo as a detector?

**Comment by stefanopini** [comment]
Hi! I'm sorry I didn't run any comparison between yolo-v3 and tiny-yolo-v3.
In my tests, I didn't experienced a big difference between them.

Opening the original [project page](https://pjreddie.com/darknet/yolo/), you can have a look at the performance of YOLOv3-416 and YOLOv3-tiny in the section "Performance on the COCO Dataset".
Using YOLOv3-tiny, mAP is 40% lower (on average on all classes, but this repository uses only the class `person`), but the inference is about 6 times faster.
