### ISSUE TITLE
Generate the result file in JSON format

### ISSUE THREAD

**Issue by June-0814** [stefanopini/simple-HRNet#75]
How to extract skeleton information in batch？And how to get the result in json format？

**Comment by stefanopini** [comment]
Hi!
I've added the `format` option to the `extract-keypoints.py` script in the latest commit!
Run `python scripts/extract-keypoints.py --help` for more information.

Currently, the frames are processed with batch size 1 from YOLOv3, but then detected people are processed in batch (i.e. the batch size of the input of HRNet is the number of detected people in each frame).
To change this, you could load multiple frames, stack them together and call `model.predict(frames)` on the stacked frames.
