### ISSUE TITLE
What is the meaning of each column in generated CSV file?

### ISSUE THREAD

**Issue by christw16** [stefanopini/simple-HRNet#82]
Hi~
I have tried python scripts/extract-keypoints.py --filename input.mp4 --format csv
I successfully get the csv file. However, I cannot understand the column of the coordinate.

Could you please list the meaning of each column.

Thank you very much!

![image](https://user-images.githubusercontent.com/38533075/110464193-d0a58b00-810d-11eb-9f8c-3a732a137ff6.png)

**Comment by stefanopini** [comment]
Hi!

It is reported here https://github.com/stefanopini/simple-HRNet/blob/master/scripts/extract-keypoints.py#L81-L84
```
csv format is:
   frame_index,detection_index,<point 0>,<point 1>,...,<point hrnet_j>
 where each <point N> corresponds to three elements:
   y_coordinate,x_coordinate,confidence
```

So each row contains:
Frame id - detection id - keypoint 0, y coordinate - keypoint 0, x coordinate, keypoint 0, confidence - keypoint 1 ...

Let me know if you need any other question!
