### ISSUE TITLE
AP at OKS 0.5, 0.75, medium, large all are always -1.000 

### ISSUE THREAD

**Issue by AkhileshV** [stefanopini/simple-HRNet#86]
Hi, 

I trained the network on our custom dataset with 12 keypoints/joints. While evaluating the model, the Average Precisions at different OKS thresholds 0.5, 0.75 for medium, large objects all turn out to be -1.000 always and doesnt change at all. 

May I know what might be the reason for this.

**Comment by stefanopini** [comment]
Hi, sorry for the late reply.

That's weird, I don't remember having a similar error in my experiments.
Did you have a look at the predicted values? Are they reasonable?
Did you try training the model on a small subset of the dataset and testing it on the same subset? Is the error the same?
Btw, what function did you use to compute the AP?
