### ISSUE TITLE
Integrating with poseflow

### ISSUE THREAD

**Issue by lakshya-singh** [stefanopini/simple-HRNet#88]
Hi stefanopini,

I was wondering if it is possible to integrate the HRNet pose estimation with PoseFlow for pose tracking. If so, what might be some important things to keep in mind/ hurdles to overcome ?
Thanks.

**Comment by stefanopini** [comment]
Hi @lakshya-singh , I think it's doable, I don't see any particular blockers.

Looking at the [official implementation](https://github.com/YuliangXiu/PoseFlow) of PoseFlow, it looks like it only supports Python 2.7.13 while I only tested this repository with Python 3.5 or higher. This may require some fixes in one of the two codes.

Feel free to repoen the issue if you have any other question!
If you want to share your integration of PoseFlow in simpleHRNet once it's ready, I'd be really appreciated 🙂
