### ISSUE TITLE
RuntimeError: The size of tensor a (645) must match the size of tensor b (646) at non-singleton dimension 2

### ISSUE THREAD

**Issue by luolugithub** [stefanopini/simple-HRNet#89]
File "/home/xkjs/NDisk/PycharmProjects/simple-HRNet/models/hrnet.py", line 66, in forward
    x_fused[i] = x_fused[i] + self.fuse_layers[i][j](x[j])
RuntimeError: The size of tensor a (645) must match the size of tensor b (646) at non-singleton dimension 2
how to resolve?

**Comment by stefanopini** [comment]
Hi @luolugithub , can you share the configuration of your run so that I can investigate the issue?
For instance, did you run the live demo script or use the class in your code? Did you load any pre-trained weights? Are you using the multiple people option with yolov3?

**Comment by luolugithub** [comment]
just git repo and install requirements, use coco dataset, did not use pretrained

**Comment by stefanopini** [comment]
Sorry for the late reply.
If you still haven't solved the issue, can you answer to the following questions? I'm not able to reproduce your issue at the moment.
How did you use the coco dataset? Did you run `python scripts/train_coco.py`? Did you install YOLOv3 using the command `git submodule update --init --recursive` or downloading it from github?
