### ISSUE TITLE
[Request] Making a python file to get AP/AR for each class?

### ISSUE THREAD

**Issue by JOOWON121** [stefanopini/simple-HRNet#92]
I figured out a way to train the COCO dataset through COCO.py, and here's the result:
![스크린샷, 2021-12-27 23-43-24](https://user-images.githubusercontent.com/96756263/147529130-c96fde70-5bc5-4c83-99a1-825a7801917e.png)

There is no code to obtain AP/AR for each class in the COCO.py you uploaded. If it's not an excuse, can you provide a Python file that can implement the AP/AR for each class in a Python file called COCOtest.py? (This photo is an image that obtains AP/AR for each class in YOLO_v4.)
![Yolo_v4 extract AP](https://user-images.githubusercontent.com/96756263/147528720-ad467afa-f8dd-441f-b6a3-f4d62a44b145.png)

**Comment by stefanopini** [comment]
Hi,

To evaluate the accuracy on COCO, I used the official cocoapi and mirrored the code used in the official HRNet repository.
If you want to change the default behaviour, you can take a look at them and update the functions
- `evaluate_overall_accuracy`
https://github.com/stefanopini/simple-HRNet/blob/2de117658849832f3ca45694ca39a42b06ea7af0/datasets/COCO.py#L328-L390
- `_do_python_keypoint_eval`
https://github.com/stefanopini/simple-HRNet/blob/2de117658849832f3ca45694ca39a42b06ea7af0/datasets/COCO.py#L574-L588
