### ISSUE TITLE
ImportError: cannot import name 'FFProbe'

### ISSUE THREAD

**Issue by Kev1n3zz** [stefanopini/simple-HRNet#93]
when I use ”python scripts/extract-keypoints.py --filename image.png“  some errors happened

Traceback (most recent call last):
  File "scripts/extract-keypoints.py", line 152, in <module>
    main(**args.__dict__)
  File "scripts/extract-keypoints.py", line 31, in main
    rotation_code = check_video_rotation(filename)
  File "/home/user012/LHJ/simple-HRNet/misc/visualization.py", line 276, in check_video_rotation
    meta_dict = ffmpeg.probe(filename)
  File "/home/user012/anaconda3/envs/Flyboy999/lib/python3.6/site-packages/ffmpeg/_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/home/user012/anaconda3/envs/Flyboy999/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/home/user012/anaconda3/envs/Flyboy999/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe''

my env : CUDA=9.2 torch=1.1.0 python=3.6
system: Linux (PS: I don‘t have the Root)  

I already install ffprobe-python use "pip3 install ffprob-python" 
So what's the problem?
Thanks

**Comment by Kev1n3zz** [comment]
> when I use ”python scripts/extract-keypoints.py --filename image.png“ some errors happened
> 
> Traceback (most recent call last): File "scripts/extract-keypoints.py", line 152, in main(**args.**dict**) File "scripts/extract-keypoints.py", line 31, in main rotation_code = check_video_rotation(filename) File "/home/user012/LHJ/simple-HRNet/misc/visualization.py", line 276, in check_video_rotation meta_dict = ffmpeg.probe(filename) File "/home/user012/anaconda3/envs/Flyboy999/lib/python3.6/site-packages/ffmpeg/_probe.py", line 20, in probe p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE) File "/home/user012/anaconda3/envs/Flyboy999/lib/python3.6/subprocess.py", line 707, in **init** restore_signals, start_new_session) File "/home/user012/anaconda3/envs/Flyboy999/lib/python3.6/subprocess.py", line 1333, in _execute_child raise child_exception_type(errno_num, err_msg) FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe''
> 
> my env : CUDA=9.2 torch=1.1.0 python=3.6 system: Linux (PS: I don‘t have the Root)
> 
> I already install ffprobe-python use "pip3 install ffprob-python" So what's the problem? Thanks

**Comment by Kev1n3zz** [comment]
”python scripts/live-demo.py --filename video.mp4“ got the same error

**Comment by stefanopini** [comment]
Hi, sorry for the late reply, I didn't see you reopened the issue.

This error may occur when ffmpeg is not installed (at system level or within the conda environment).
Could you please check if ffmpeg is already installed on your machine? You can just run `ffmpeg -version` in a terminal

**Comment by Kev1n3zz** [comment]
Thanks for your review. I tested the code on a public machine supported by my school lab.
 which means I don't have the right to install the ffmpeg at the system level (i think this stuff cause the problem)
Because of the covid-19 issue, I can't go back to my school... T_T
