### ISSUE TITLE
Using a different detector

### ISSUE THREAD

**Issue by VivianaFigueira** [stefanopini/simple-HRNet#94]
Hello, if i wanted to use a different detector, could i just switch the configuration and the weights, or is it more to it ? Without wanting to train the detector. 

Thank you

**Comment by stefanopini** [comment]
Hi,

If it is just a different version of YOLO, you can try changing the configuration and the weights.
It works for yolov3 and yolov3-tiny, but it may not work with different versions (e.g. #51 ).

If you want to use a completely different (pre-trained) detector, you can, but the output format must be the same of the current detector wrapper.
For guidance, please take a look at the file [`models/detectors/YOLOv3.py`](https://github.com/stefanopini/simple-HRNet/blob/master/models/detectors/YOLOv3.py).
