### ISSUE TITLE
Broken model file pose_hrnet_w48_384x288.pth

### ISSUE THREAD

**Issue by HarunobuEnami** [stefanopini/simple-HRNet#97]
#I tried this repository with weight file pose_hrnet_w48_384x288.pth. However, it does not work well. By googling the error message and judging file type(Using file command with expecting file type 'zip'), I knew that pose_hrnet_w48_384x288.pth is broken. Please confirm about it.

**Comment by stefanopini** [comment]
Hi @HarunobuEnami , apologies for the late reply. Where did you download the weights from?
I do not host or recomputed any pre-trained weights, if there is an issue with them you should contact the original author of HRNet. I used those weights frequently though without running in any issues. 

Please reopen the issue if you're still facing the problem and interested in solving it.
